### ISSUE TITLE
FluentSelect is still in CsvReaderBenchmarks

### ISSUE THREAD

**Issue by airbreather** [MarkPflug/CsvBenchmarks#3]
`CsvReaderBenchmarks.FluentSelect` is still just selecting columns 0, 10, and 20, even though everything in `CsvReaderBenchmarks` should be processing all fields.

**Comment by MarkPflug** [comment]
Yeah, I realized it was not a fair test. Honestly, I was too lazy to write an accessor that touched every column, and even with this unfair test Fluent is the slowest. It looks Joel Verhagen uses a [lower-level mechanism](https://github.com/joelverhagen/NCsvPerf/blob/586f6020781925b20d4f071d4ecfa01e1572d5b6/NCsvPerf/CsvReadable/Implementations/FluentCsv.cs#L26-L34) in that library that I should be duplicating here, which makes it easier (loop) to touch every column.

You should send Joel a PR for his benchmarks too. You'd probably crush in his benchmarks.

**Comment by airbreather** [comment]
> You should send Joel a PR for his benchmarks too. You'd probably crush in his benchmarks.

I originally looked into it back when his post was making the rounds on Reddit, but the end goal was to produce something with way too many fields that needed to become individual UTF-16 `string` instances.

**Comment by MarkPflug** [comment]
The way that I crushed Joel's benchmarks was by enabling pooling of strings; real pooling, not just the single-char hack that I used in this repo. The "trick" is that his dataset is highly repetitive due to the way he constructs it, so after the first few thousand strings everything ends up being a duplicate. My string pool implementation works on char[], but you could implement a similar one that consumes byte[] instead. I'd be surprised if you didn't take the lead with the same technique.

**Comment by airbreather** [comment]
Hm, that's actually really interesting.  I'll give it a try in the next few days and see.

**Comment by MarkPflug** [comment]
Update fluent to touch every column. oof, that hurts.

> that's actually really interesting

One of the few novel ideas my library has, so at the very least maybe the competition will cause it to find it's way into other libraries that people actually use. I know there has been some discussion about adding string de-duping to the runtime. I wonder if it isn't better to attack the problem from the other end, by identifying the source of duplicate strings, instead of trying to de-duplicate strings after the fact, which has other concerning implications. See issue 9022 in the dotnet/runtime repo (I'm intentionally trying to *not* link to it).
